@startuml Activity
(*) --> "ブログの表示" 
note left: ここでは円グラフの描画を行うタイミングと考える
partition "データ取得" {
"ブログの表示" --> ===fork===
===fork=== --> "現在のカテゴリデータの取得"
--> ===join===
===fork=== --> "今までのカテゴリデータ(累計)の取得"
--> ===join===
}

if "データが等しい" then 
note right: データが等しければ何もせず表示処理へ
--> [Yes] "円グラフでカテゴリデータを表示する"
else
partition "データ操作と再取得" { 
--> [No] "スプレッドシートのデータを更新する" 
--> "描画用のカテゴリデータの再設定"
--> "円グラフでカテゴリデータを表示する" 
}
endif
--> (*)
@enduml