
@startuml Activity

(*) --> "ブログの表示" 
note left: ここでは円グラフが含まれるページの表示をする全ての状況
if "現在のセッションの状態" then
note right: セッションが継続中なら\n表示処理を再度呼び出すことはしない
--> "円グラフでカテゴリデータを表示する" 
else 
note left: 新しくセッションを開始した、\nまたはセッション開始から30分経過した
partition "データ取得" {
--> ===fork=== 
--> "現在のカテゴリデータの取得"
--> ===join===
===fork=== --> "今までのカテゴリデータ(累計)の取得"
--> ===join===
}
endif

if "データが等しい" then 
note right: データが等しければ何もせず表示処理へ
--> [Yes] "円グラフでカテゴリデータを表示する"
else
partition "データ更新関連処理" { 
--> [No] "スプレッドシートのデータを更新する" 
--> "描画用のカテゴリデータの再設定"
--> "円グラフでカテゴリデータを表示する" 
}
endif
--> (*)

@enduml